modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/InnovativeOnlineIndustries/Emojiful/issues"
side="CLIENT"
license="ARR"

[[mods]]
    modId="emojiful"
    version="${file.jarVersion}"
    displayName="Emojiful"
    authors="HRZN"
    description='''
    Adds Emojis to the Game Chat!!!
    '''
    mandatory=false
    side="CLIENT"

[[dependencies.emojiful]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.emojiful]]
    modId="forge"
    mandatory=true
    versionRange="[41.1.0,)"
    ordering="NONE"
    side="CLIENT"
