modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/InnovativeOnlineIndustries/Emojiful/issues"
side="CLIENT"

[[mods]]
    modId="emojiful"
    version="${file.jarVersion}"
    displayName="Emojiful"
    authors="HRZN"
    description='''
    Adds Emotes to the Game Chat!!!
    '''
    mandatory=false
    side="CLIENT"

[[dependencies.emojiful]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="CLIENT"
